=== ASU-Capstone/uPortal-Capstone/uportal-war/src/main/resources/xsd/io/permission-owner/permission-owner-4.0.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

    Licensed to Apereo under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Apereo licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License.  You may obtain a
    copy of the License at the following location:

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.

-->
<xs:schema
    xmlns="https://source.jasig.org/schemas/uportal/io/permission-owner"
    targetNamespace="https://source.jasig.org/schemas/uportal/io/permission-owner"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:up="https://source.jasig.org/schemas/uportal"
    xmlns:io="https://source.jasig.org/schemas/uportal/io"
    elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">

    <xs:import namespace="https://source.jasig.org/schemas/uportal" schemaLocation="../../common-types-4.0.xsd"/>
    <xs:import namespace="https://source.jasig.org/schemas/uportal/io" schemaLocation="../common-io-types-4.0.xsd"/>

    <xs:element name="permission-owner">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="io:basePortalDataType40">
                    <xs:sequence>
                        <xs:element name="name" type="xs:string"/>
                        <xs:element name="fname" type="up:fname-type"/>
                        <xs:element name="desc" type="xs:string" minOccurs="0"/>
                        
                        <xs:element name="activity" type="externalActivity" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
        <xs:unique name="unique-activity">
            <xs:selector xpath="activity"/>
            <xs:field xpath="fname"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="externalActivity">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="fname" type="up:fname-type"/>
            <xs:element name="desc" type="xs:string" minOccurs="0"/>
            <xs:element name="targetProvider" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== ASU-Capstone/uPortal-Capstone/uportal-war/src/main/data/default_entities/permission_owner/UP_FRAGMENT.permission-owner.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

    Licensed to Apereo under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Apereo licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License.  You may obtain a
    copy of the License at the following location:

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.

-->
<permission-owner xmlns="https://source.jasig.org/schemas/uportal/io/permission-owner" xmlns:ns2="https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor" xmlns:ns3="https://source.jasig.org/schemas/uportal/io/portlet-definition" xmlns:ns4="https://source.jasig.org/schemas/uportal" xmlns:ns5="https://source.jasig.org/schemas/uportal/io/portlet-type" xmlns:ns6="https://source.jasig.org/schemas/uportal/io/user" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="4.0" xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/permission-owner https://source.jasig.org/schemas/uportal/io/permission-owner/permission-owner-4.0.xsd">
    <name>Fragments</name>
    <fname>UP_FRAGMENT</fname>
    <desc>Permissions controlling uPortal DLM fragments</desc>
    <activity>
        <name>Fragment Subscription</name>
        <fname>FRAGMENT_SUBSCRIBE</fname>
        <desc>Subscribe to a pulled fragment</desc>
        <targetProvider>peopleAndGroupsTargetProvider</targetProvider>
    </activity>
</permission-owner>

=== ASU-Capstone/uPortal-Capstone/uportal-war/src/main/data/default_entities/permission_owner/UP_USERS.permission-owner.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

    Licensed to Apereo under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Apereo licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License.  You may obtain a
    copy of the License at the following location:

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.

-->
<permission-owner xmlns="https://source.jasig.org/schemas/uportal/io/permission-owner" xmlns:ns2="https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor" xmlns:ns3="https://source.jasig.org/schemas/uportal/io/portlet-definition" xmlns:ns4="https://source.jasig.org/schemas/uportal" xmlns:ns5="https://source.jasig.org/schemas/uportal/io/portlet-type" xmlns:ns6="https://source.jasig.org/schemas/uportal/io/user" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="4.0" xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/permission-owner https://source.jasig.org/schemas/uportal/io/permission-owner/permission-owner-4.0.xsd">
    <name>Users</name>
    <fname>UP_USERS</fname>
    <desc>Permissions controlling uPortal user account management</desc>
    <activity>
        <name>View user attribute</name>
        <fname>VIEW_USER_ATTRIBUTE</fname>
        <desc>View a specific user attribute.  This permission applies to that attribute for all visible users</desc>
        <targetProvider>userAttributesTargetProvider</targetProvider>
    </activity>
    <activity>
        <name>View user</name>
        <fname>VIEW_USER</fname>
        <desc>View a user.</desc>
        <targetProvider>peopleAndGroupsTargetProvider</targetProvider>
    </activity>
    <activity>
        <name>Delete users</name>
        <fname>DELETE_USER</fname>
        <desc>Delete local uPortal accounts</desc>
        <targetProvider>peopleAndGroupsTargetProvider</targetProvider>
    </activity>
    <activity>
        <name>Edit user attribute</name>
        <fname>EDIT_USER_ATTRIBUTE</fname>
        <desc>Edit a specific user attribute.  This permission applies to that attribute for all editable users</desc>
        <targetProvider>userAttributesTargetProvider</targetProvider>
    </activity>
    <activity>
        <name>Edit users</name>
        <fname>EDIT_USER</fname>
        <desc>Edit local uPortal accounts</desc>
        <targetProvider>peopleAndGroupsTargetProvider</targetProvider>
    </activity>
    <activity>
        <name>Impersonate users</name>
        <fname>IMPERSONATE</fname>
        <desc>Impersonate users for debugging purposes in uPortal</desc>
        <targetProvider>peopleAndGroupsTargetProvider</targetProvider>
    </activity>
</permission-owner>

=== ASU-Capstone/uPortal-Capstone/uportal-war/src/main/data/default_entities/permission_owner/UP_PORTLET_PUBLISH.permission-owner.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

    Licensed to Apereo under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Apereo licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License.  You may obtain a
    copy of the License at the following location:

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.

-->
<permission-owner xmlns="https://source.jasig.org/schemas/uportal/io/permission-owner" xmlns:ns2="https://source.jasig.org/schemas/uportal/io/stylesheet-descriptor" xmlns:ns3="https://source.jasig.org/schemas/uportal/io/portlet-definition" xmlns:ns4="https://source.jasig.org/schemas/uportal" xmlns:ns5="https://source.jasig.org/schemas/uportal/io/portlet-type" xmlns:ns6="https://source.jasig.org/schemas/uportal/io/user" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="4.0" xsi:schemaLocation="https://source.jasig.org/schemas/uportal/io/permission-owner https://source.jasig.org/schemas/uportal/io/permission-owner/permission-owner-4.0.xsd">
    <name>Portlet Publishing</name>
    <fname>UP_PORTLET_PUBLISH</fname>
    <desc>Permissions controlling the publishing and editing of uPortal content</desc>
    <activity>
        <name>Select Portlet Type</name>
        <fname>SELECT_PORTLET_TYPE</fname>
        <desc>Select the specified portlet type when publishing a new portlet.</desc>
        <targetProvider>portletTypeTargetProvider</targetProvider>
    </activity>
    <activity>
        <name>Manage Created</name>
        <fname>MANAGE_CREATED</fname>
        <desc>Create uPortal content (portlets).</desc>
        <targetProvider>channelsAndCategoriesTargetProvider</targetProvider>
    </activity>
    <activity>
        <name>Manage Approved</name>
        <fname>MANAGE_APPROVED</fname>
        <desc>Manage approved uPortal content (portlets).  This permission also implies the ability to create portlets.</desc>
        <targetProvider>channelsAndCategoriesTargetProvider</targetProvider>
    </activity>
    <activity>
        <name>Manage Published</name>
        <fname>MANAGE</fname>
        <desc>Manage published uPortal content (portlets).  This permission also implies the ability to create and approve portlets.</desc>
        <targetProvider>channelsAndCategoriesTargetProvider</targetProvider>
    </activity>
    <activity>
        <name>Manage Expired</name>
        <fname>MANAGE_EXPIRED</fname>
        <desc>Manage expired uPortal content (portlets).  This permission also implies the ability to create, approve, and publish portlets.</desc>
        <targetProvider>channelsAndCategoriesTargetProvider</targetProvider>
    </activity>
    <activity>
        <name>Manage Maintenance</name>
        <fname>MANAGE_MAINTENANCE</fname>
        <desc>Manage uPortal content (portlets) in MAINTENANCE mode.  This permission also implies the ability to create, approve, publish, and expire portlets.</desc>
        <targetProvider>channelsAndCategoriesTargetProvider</targetProvider>
    </activity>
    <activity>
        <name>Configure</name>
        <fname>PORTLET_MODE_CONFIG</fname>
        <desc>Access the configuration mode of a portlet.</desc>
        <targetProvider>channelsAndCategoriesTargetProvider</targetProvider>
    </activity>
</permission-owner>
