=== ASU-Capstone/uPortal-Capstone/uPortal/uportal-war/src/main/resources/dtd/LDAPGroupStore.dtd
<!--

    Licensed to Apereo under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Apereo licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License.  You may obtain a
    copy of the License at the following location:

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.

-->
<!ELEMENT LDAPGroupStore (config,group)>

<!ELEMENT config (url,logonid,logonpassword,keyfield,namefield,usercontext,refresh-minutes)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT logonid (#PCDATA)>
<!ELEMENT logonpassword (#PCDATA)>
<!-- the ldap attribute that corresponds to the IPerson key (username)-->
<!ELEMENT keyfield (#PCDATA)>
<!-- the ldap attribute that corresponds to the IPerson displayname (e.g. 'cn') -->
<!ELEMENT namefield (#PCDATA)>
<!ELEMENT usercontext (#PCDATA)>
<!-- an integer indicating after how many minutes a group's memberships should be
refreshed by reloading its entity-set -->
<!ELEMENT refresh-minutes (#PCDATA)>

<!ELEMENT group (description?,entity-set?,group*)>
<!-- note that a group key must be unique within the document -->
<!ATTLIST group name CDATA #REQUIRED
	key CDATA #REQUIRED
>
<!ELEMENT description (#PCDATA)>

<!ELEMENT entity-set (filter|attributes|union|intersection|difference|subtract)>

<!-- use standard LDAP filter syntax, including wildcards -->
<!ELEMENT filter EMPTY>
<!ATTLIST filter string CDATA #REQUIRED>

<!-- match a collection of specific literal LDAP attribute values -->
<!ELEMENT attributes (attribute*)>
<!ELEMENT attribute EMPTY>
<!ATTLIST attribute name CDATA #REQUIRED
	value CDATA	#REQUIRED
>

<!-- return all results from all contained entity sets-->
<!ELEMENT union (entity-set*)>

<!-- return all common results from all contained entity sets -->
<!ELEMENT intersection (entity-set*)>

<!-- return all results that occur in only one contained entity set -->
<!ELEMENT difference (entity-set*)>

<!-- return all members of the first entity set minus any that occur in the rest -->
<!ELEMENT subtract (entity-set*)>

=== ASU-Capstone/uPortal-Capstone/uportal-war/src/main/resources/properties/groups/LDAPGroupStoreConfig.xml
<?xml version="1.0"?>
<!--

    Licensed to Apereo under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Apereo licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License.  You may obtain a
    copy of the License at the following location:

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.

-->
<!DOCTYPE LDAPGroupStore PUBLIC "-//uPortal//LDAPGroupStore/EN" "LDAPGroupStore.dtd">

<!--
	LDAPGroupStoreConfig.xml is used to configure the default LDAP group store.
	Additional LDAP group stores can be configured by creating additional configuration
	documents, and cerating an IGroupServiceFactory implementation that instantiates
	a new LDAPGroupStore with the other configuration document as an argument to
	the constructor.

	See LDAPGroupStore.dtd for xml grammar.

	NOTE: For demonstration purposes, this document contains Columbia-specific
        configuration information.  This should be replaced with a configuration
        suitable to your institution

     Author: Alex Vigdor, av317@columbia.edu
     Version $Revision$
-->

<LDAPGroupStore>
	<config>
		<url>ldap://ldap.columbia.edu:389/o=Columbia%20University,c=US</url>
		<logonid></logonid>
		<logonpassword></logonpassword>
		<keyfield>uni</keyfield>
		<namefield>cn</namefield>
		<usercontext></usercontext>
		<refresh-minutes>120</refresh-minutes>
	</config>
        <group name="All LDAP Groups" key = "all">
          <description>The root of all LDAP-derived groups</description>
          <group name="Vigdors" key="1">
                  <description>All people with the last name Vigdor</description>
                  <entity-set>
                          <filter string="cn=*vigdor"/>
                  </entity-set>
          </group>
          <group name="Fracapanes and Ellentucks" key="2">
                  <description>All Fracapanes and Ellentucks out there</description>
                  <entity-set>
                          <union>
                                  <entity-set>
                                          <filter string="cn=*fracapane"/>
                                  </entity-set>
                                  <entity-set>
                                          <filter string="cn=*ellentuck"/>
                                  </entity-set>
                          </union>
                  </entity-set>
          </group>
          <group name="Union test" key="3">
                  <entity-set>
                          <union>
                                  <entity-set>
                                          <filter string="cn=donald f*"/>
                                  </entity-set>
                                  <entity-set>
                                          <filter string="cn=*frac*"/>
                                  </entity-set>
                          </union>
                  </entity-set>
          </group>
          <group name="Intersection test" key="4">
                  <entity-set>
                          <intersection>
                                  <entity-set>
                                          <filter string="cn=donald f*"/>
                                  </entity-set>
                                  <entity-set>
                                          <filter string="cn=*frac*"/>
                                  </entity-set>
                          </intersection>
                  </entity-set>
          </group>
          <group name="Difference test" key="5">
                  <entity-set>
                          <difference>
                                  <entity-set>
                                          <filter string="cn=donald f*"/>
                                  </entity-set>
                                  <entity-set>
                                          <filter string="cn=*frac*"/>
                                  </entity-set>
                          </difference>
                  </entity-set>
          </group>
          <group name="Subtract test" key="6">
                  <entity-set>
                          <subtract>
                                  <entity-set>
                                          <filter string="cn=donald f*"/>
                                  </entity-set>
                                  <entity-set>
                                          <filter string="cn=*frac*"/>
                                  </entity-set>
                          </subtract>
                  </entity-set>
          </group>
      </group>
</LDAPGroupStore>
