=== ASU-Capstone/uPortal-Capstone/uportal-war/src/main/resources/xsd/io/event-aggregation/event-aggregation-4.0.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

    Licensed to Apereo under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Apereo licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License.  You may obtain a
    copy of the License at the following location:

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.

-->
<xs:schema
    xmlns="https://source.jasig.org/schemas/uportal/io/event-aggregation"
    targetNamespace="https://source.jasig.org/schemas/uportal/io/event-aggregation"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:up="https://source.jasig.org/schemas/uportal"
    xmlns:io="https://source.jasig.org/schemas/uportal/io"
    elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">

    <xs:import namespace="https://source.jasig.org/schemas/uportal" schemaLocation="../../common-types-4.0.xsd"/>
    <xs:import namespace="https://source.jasig.org/schemas/uportal/io" schemaLocation="../common-io-types-4.0.xsd"/>

    <xs:element name="event-aggregation">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="io:basePortalDataType40">
                    <xs:sequence>
                        <xs:element name="aggregated-group-config" type="externalAggregatedGroupConfig" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:element name="aggregated-interval-config" type="externalAggregatedIntervalConfig" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:element name="quarter-details" type="externalQuarterDetail" minOccurs="0" maxOccurs="4"/>
                        <xs:element name="term-details" type="externalTermDetail" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
        <xs:unique name="unique-aggregated-group-config">
            <xs:selector xpath="aggregated-group-config"/>
            <xs:field xpath="aggregator-type"/>
        </xs:unique>
        <xs:unique name="unique-aggregated-interval-config">
            <xs:selector xpath="aggregated-interval-config"/>
            <xs:field xpath="aggregator-type"/>
        </xs:unique>
        <xs:unique name="unique-quarter-details">
            <xs:selector xpath="quarter-details"/>
            <xs:field xpath="id"/>
        </xs:unique>
        <xs:unique name="unique-term-details">
            <xs:selector xpath="term-details"/>
            <xs:field xpath="name"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="externalAggregatedDimensionConfig" abstract="true">
        <xs:sequence>
            <xs:element name="aggregator-type" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="externalAggregatedGroupConfig">
        <xs:complexContent>
            <xs:extension base="externalAggregatedDimensionConfig">
                <xs:sequence>
                    <xs:element name="include" type="externalAggregatedGroupMapping" minOccurs="0"  maxOccurs="unbounded"/>
                    <xs:element name="exclude" type="externalAggregatedGroupMapping" minOccurs="0"  maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="externalAggregatedIntervalConfig">
        <xs:complexContent>
            <xs:extension base="externalAggregatedDimensionConfig">
                <xs:sequence>
                    <xs:element name="include" type="externalAggregationInterval" minOccurs="0"  maxOccurs="unbounded"/>
                    <xs:element name="exclude" type="externalAggregationInterval" minOccurs="0"  maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="externalAggregatedGroupMapping">
        <xs:sequence>
            <xs:element name="groupService" type="xs:string"/>
            <xs:element name="groupName" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="externalAggregationInterval">
        <xs:restriction base="xs:string">
            <xs:enumeration value="MINUTE"/>
            <xs:enumeration value="FIVE_MINUTE"/>
            <xs:enumeration value="HOUR"/>
            <xs:enumeration value="DAY"/>
            <xs:enumeration value="WEEK"/>
            <xs:enumeration value="MONTH"/>
            <xs:enumeration value="CALENDAR_QUARTER"/>
            <xs:enumeration value="ACADEMIC_TERM"/>
            <xs:enumeration value="YEAR"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="externalQuarterDetail">
        <xs:sequence>
            <xs:element name="id" type="externalQuarterId" />
            <xs:element name="start" type="xs:string" />
            <xs:element name="end" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="externalQuarterId">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0" />
            <xs:maxInclusive value="3" />
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="externalTermDetail">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="start" type="xs:date" />
            <xs:element name="end" type="xs:date" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== ASU-Capstone/uPortal-Capstone/uportal-war/src/test/resources/org/jasig/portal/io/xml/eventaggr/test_4-0.event-aggregation.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

    Licensed to Apereo under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Apereo licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License.  You may obtain a
    copy of the License at the following location:

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.

-->
<event-aggregation
    xmlns="https://source.jasig.org/schemas/uportal/io/event-aggregation"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="
        https://source.jasig.org/schemas/uportal/io/event-aggregation https://source.jasig.org/schemas/uportal/io/event-aggregation/event-aggregation-4.0.xsd"
    version="4.0">
     
    <aggregated-group-config>
        <aggregator-type>org.jasig.portal.events.aggr.login.LoginPortalEventAggregator</aggregator-type>
        <exclude>
            <groupService>local</groupService>
            <groupName>Guest</groupName>
        </exclude>
    </aggregated-group-config>
    
    <aggregated-interval-config>
        <aggregator-type>org.jasig.portal.events.aggr.IPortalEventAggregator</aggregator-type>
        <exclude>MINUTE</exclude>
    </aggregated-interval-config>
    
    <quarter-details>
        <id>0</id>
        <start>--01-01</start>
        <end>--04-01</end>
    </quarter-details>
    <quarter-details>
        <id>1</id>
        <start>--04-01</start>
        <end>--07-01</end>
    </quarter-details>
    <quarter-details>
        <id>2</id>
        <start>--07-01</start>
        <end>--10-01</end>
    </quarter-details>
    <quarter-details>
        <id>3</id>
        <start>--10-01</start>
        <end>--01-01</end>
    </quarter-details>
</event-aggregation>

=== ASU-Capstone/uPortal-Capstone/uPortal/uportal-war/src/main/data/default_entities/event-aggregation/default.event-aggregation.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

    Licensed to Apereo under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Apereo licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License.  You may obtain a
    copy of the License at the following location:

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.

-->
<event-aggregation
    xmlns="https://source.jasig.org/schemas/uportal/io/event-aggregation"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="
        https://source.jasig.org/schemas/uportal/io/event-aggregation https://source.jasig.org/schemas/uportal/io/event-aggregation/event-aggregation-4.0.xsd"
    version="4.0">
    
    <!-- 
     | Only aggregate data for the local.Everyone group to reduce storage requirements
     +-->
    <aggregated-group-config>
        <aggregator-type>org.jasig.portal.events.aggr.IPortalEventAggregator</aggregator-type>
        <include>
            <groupService>local</groupService>
            <groupName>Everyone</groupName>
        </include>
        <include>
            <groupService>local</groupService>
            <groupName>Students</groupName>
        </include>
    </aggregated-group-config>
    
    <!-- 
     | Setup conservative list of included intervals to reduce storage requirements.
     +-->
    <aggregated-interval-config>
        <aggregator-type>org.jasig.portal.events.aggr.concuser.ConcurrentUserAggregator</aggregator-type>
        <include>FIVE_MINUTE</include>
    </aggregated-interval-config>
    <aggregated-interval-config>
        <aggregator-type>org.jasig.portal.events.aggr.login.LoginPortalEventAggregator</aggregator-type>
        <include>FIVE_MINUTE</include>
        <include>HOUR</include>
        <include>DAY</include>
        <include>MONTH</include>
    </aggregated-interval-config>
    <aggregated-interval-config>
        <aggregator-type>org.jasig.portal.events.aggr.portletexec.PortletExecutionAggregator</aggregator-type>
        <include>HOUR</include>
        <include>DAY</include>
        <include>MONTH</include>
    </aggregated-interval-config>
    <aggregated-interval-config>
        <aggregator-type>org.jasig.portal.events.aggr.tabrender.TabRenderAggregator</aggregator-type>
        <include>HOUR</include>
        <include>DAY</include>
        <include>MONTH</include>
    </aggregated-interval-config>
    <aggregated-interval-config>
        <aggregator-type>org.jasig.portal.events.aggr.portletlayout.PortletLayoutAggregator</aggregator-type>
        <include>DAY</include>
        <include>MONTH</include>
    </aggregated-interval-config>
    <aggregated-interval-config>
        <aggregator-type>org.jasig.portal.events.aggr.action.SearchRequestAggregator</aggregator-type>
        <include>FIVE_MINUTE</include>
        <include>HOUR</include>
        <include>DAY</include>
    </aggregated-interval-config>
    <quarter-details>
        <id>0</id>
        <start>--01-01</start>
        <end>--04-01</end>
    </quarter-details>
    <quarter-details>
        <id>1</id>
        <start>--04-01</start>
        <end>--07-01</end>
    </quarter-details>
    <quarter-details>
        <id>2</id>
        <start>--07-01</start>
        <end>--10-01</end>
    </quarter-details>
    <quarter-details>
        <id>3</id>
        <start>--10-01</start>
        <end>--01-01</end>
    </quarter-details>
    
    <!-- Example term configuration data 
    <term-details>
      <name>Fall 2011-2012</name>
      <start>2011-08-29</start>
      <end>2011-12-24</end>
    </term-details>
    <term-details>
      <name>Winter 2011-2012</name>
      <start>2011-12-24</start>
      <end>2012-02-13</end>
    </term-details>
    <term-details>
      <name>Spring 2011-2012</name>
      <start>2012-02-13</start>
      <end>2012-05-21</end>
    </term-details>
    <term-details>
      <name>Summer 2012</name>
      <start>2012-05-21</start>
      <end>2012-08-27</end>
    </term-details>
    <term-details>
      <name>Fall 2012-2013</name>
      <start>2012-08-27</start>
      <end>2012-12-24</end>
    </term-details>
    <term-details>
      <name>Spring 2012-2013</name>
      <start>2012-12-24</start>
      <end>2013-05-20</end>
    </term-details>
    <term-details>
      <name>Summer 2013</name>
      <start>2013-05-20</start>
      <end>2013-08-26</end>
    </term-details>
    <term-details>
      <name>Fall 2013-2014</name>
      <start>2013-08-26</start>
      <end>2013-12-23</end>
    </term-details>
     -->
</event-aggregation>
